# Generated by Django 6.0 on 2025-12-11 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('icmp', 'ICMP/Ping'), ('tcp', 'TCP')], default='https', max_length=10)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=443)),
                ('path', models.CharField(blank=True, default='/', help_text='URL path for HTTP/HTTPS checks', max_length=500)),
                ('check_interval', models.IntegerField(default=300, help_text='Check interval in seconds')),
                ('timeout', models.IntegerField(default=10, help_text='Timeout in seconds')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], db_index=True, default='active', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('notify_on_failure', models.BooleanField(default=True)),
                ('notify_recovery', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status', 'updated_at'], name='monitoring__status_13f0b8_idx'), models.Index(fields=['protocol', 'host'], name='monitoring__protoco_93f14d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('degraded', 'Degraded'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('uptime_percentage', models.FloatField(default=100.0)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('last_up', models.DateTimeField(blank=True, null=True)),
                ('last_down', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('failure_threshold', models.IntegerField(default=3, help_text='Number of failures before marking as down')),
                ('message', models.TextField(blank=True, null=True)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_status', to='monitoring.server')),
            ],
            options={
                'ordering': ['server__name'],
            },
        ),
        migrations.CreateModel(
            name='PingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('timeout', 'Timeout'), ('error', 'Error')], db_index=True, max_length=20)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('check_timestamp', models.DateTimeField(db_index=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ping_results', to='monitoring.server')),
            ],
            options={
                'ordering': ['-check_timestamp'],
                'indexes': [models.Index(fields=['server', '-check_timestamp'], name='monitoring__server__e0056d_idx'), models.Index(fields=['status', 'check_timestamp'], name='monitoring__status_3fa7e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook'), ('sms', 'SMS')], max_length=20)),
                ('recipient', models.CharField(help_text='Email, phone number, or webhook URL', max_length=500)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('notify_on_failure', models.BooleanField(default=True)),
                ('notify_on_recovery', models.BooleanField(default=True)),
                ('min_notification_interval', models.IntegerField(default=300, help_text='Minimum interval between notifications in seconds')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_configs', to='monitoring.server')),
            ],
            options={
                'ordering': ['server', 'notification_type'],
                'unique_together': {('server', 'notification_type', 'recipient')},
            },
        ),
    ]
