# Generated by Django 6.0 on 2025-12-11 17:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('included_sms', models.IntegerField(default=0)),
                ('included_emails', models.IntegerField(default=0)),
                ('price_per_extra_sms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('price_per_extra_email', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
            ],
            options={
                'ordering': ['monthly_price'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='server',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sms_credits', models.IntegerField(default=0)),
                ('email_credits', models.IntegerField(default=0)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
                'abstract': False,
            },
        ),
    ]
