# Generated by Django 6.0 on 2025-12-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_useraccount_user_organization_membership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingresult',
            name='avg',
            field=models.FloatField(blank=True, help_text='Average round-trip time in ms for ICMP checks', null=True),
        ),
        migrations.AddField(
            model_name='pingresult',
            name='loss',
            field=models.IntegerField(blank=True, help_text='Packet loss percentage (0-100) for ICMP checks', null=True),
        ),
        migrations.AddField(
            model_name='pingresult',
            name='received',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pingresult',
            name='transmitted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='loss_rate_threshold',
            field=models.IntegerField(default=50, help_text='Maximum acceptable packet loss percentage before flagging issues'),
        ),
    ]
